// vue-implementation/src/components/Header.vue
<template>
  <header class="site-header">
    <div class="container header-inner">
      <div class="brand">
        <router-link to="/" class="logo-link" aria-label="Ticket App Home">
          <strong class="app-name">Ticketr</strong>
        </router-link>
      </div>

      <!-- Mobile Menu Button -->
      <button 
        :class="['mobile-menu-btn', { open: menuOpen }]"
        @click="toggleMenu"
        :aria-expanded="menuOpen"
        aria-controls="main-nav"
        aria-label="Toggle navigation menu"
      >
        <span class="sr-only">Menu</span>
        <span class="hamburger"></span>
      </button>

      <nav 
        id="main-nav" 
        :class="['main-nav', { open: menuOpen }]"
        aria-label="Main navigation"
      >
        <router-link 
          v-for="route in routes" 
          :key="route.path"
          :to="route.path"
          :class="{ active: currentPath === route.path }"
        >
          {{ route.name }}
        </router-link>
      </nav>

      <div class="header-actions">
        <template v-if="isAuthenticated">
          <span class="username" :title="session?.username">{{ session?.username }}</span>
          <button class="btn ghost" @click="handleLogout">Logout</button>
        </template>
        <template v-else>
          <router-link to="/auth/login" class="btn ghost">Login</router-link>
          <router-link to="/auth/signup" class="btn primary">Get Started</router-link>
        </template>
      </div>
    </div>
  </header>
</template>

<script setup>
import { ref, onMounted, onUnmounted, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuth } from '../hooks/useAuth'

const route = useRoute()
const router = useRouter()
const { isAuthenticated, session, logout } = useAuth()

const menuOpen = ref(false)
const currentPath = ref(route.path)

const routes = [
  { path: '/', name: 'Home' },
  { path: '/dashboard', name: 'Dashboard' },
  { path: '/tickets', name: 'Tickets' }
]

// Watch route changes to close menu and update current path
watch(() => route.path, (newPath) => {
  menuOpen.value = false
  currentPath.value = newPath
})

// Handle escape key to close menu
const handleEscape = (e) => {
  if (e.key === 'Escape') menuOpen.value = false
}

onMounted(() => {
  document.addEventListener('keydown', handleEscape)
})

onUnmounted(() => {
  document.removeEventListener('keydown', handleEscape)
})

const toggleMenu = () => {
  menuOpen.value = !menuOpen.value
}

const handleLogout = async () => {
  await logout()
  router.push('/')
}
</script>

<style>
@import '../styles/header.css';
</style>

// react-implementation/src/components/Header.jsx
import React, { useContext, useState, useEffect } from 'react'
import { Link, useNavigate, useLocation } from 'react-router-dom'
import { AuthContext } from '../contexts/context'
import '../styles/header.css'

export default function Header(){
  const { isAuthenticated, session, logout } = useContext(AuthContext)
  const nav = useNavigate()
  const location = useLocation()
  const [menuOpen, setMenuOpen] = useState(false)

  // Close menu on route change
  useEffect(() => {
    setMenuOpen(false)
  }, [location.pathname])

  // Close menu on escape key
  useEffect(() => {
    const handleEscape = (e) => {
      if (e.key === 'Escape') setMenuOpen(false)
    }
    document.addEventListener('keydown', handleEscape)
    return () => document.removeEventListener('keydown', handleEscape)
  }, [])

  const handleLogout = async () => {
    await logout()
    nav('/')
  }

  const toggleMenu = () => setMenuOpen(!menuOpen)

  return (
    <header className="site-header">
      <div className="container header-inner">
        <div className="brand">
          <Link to="/" className="logo-link" aria-label="Ticket App Home">
            <strong className="app-name">Ticketr</strong>
          </Link>
        </div>

        {/* Mobile Menu Button */}
        <button 
          className={`mobile-menu-btn ${menuOpen ? 'open' : ''}`}
          onClick={toggleMenu}
          aria-expanded={menuOpen}
          aria-controls="main-nav"
          aria-label="Toggle navigation menu"
        >
          <span className="sr-only">Menu</span>
          <span className="hamburger"></span>
        </button>

        <nav 
          id="main-nav" 
          className={`main-nav ${menuOpen ? 'open' : ''}`} 
          aria-label="Main navigation"
        >
          <Link to="/" className={location.pathname === '/' ? 'active' : ''}>
            Home
          </Link>
          <Link to="/dashboard" className={location.pathname === '/dashboard' ? 'active' : ''}>
            Dashboard
          </Link>
          <Link to="/tickets" className={location.pathname === '/tickets' ? 'active' : ''}>
            Tickets
          </Link>
        </nav>

        <div className="header-actions">
          {isAuthenticated ? (
            <>
              <span className="username" title={session?.username}>{session?.username}</span>
              <button className="btn ghost" onClick={handleLogout}>Logout</button>
            </>
          ) : (
            <>
              <Link to="/auth/login" className="btn ghost">Login</Link>
              <Link to="/auth/signup" className="btn primary">Get Started</Link>
            </>
          )}
        </div>
      </div>
    </header>
  )
}
