// vue-implementation/src/pages/Auth/Signup.vue
<template>
  <div class="auth-page">
    <div class="auth-card">
        <div class="auth-header">
          <h1>Create Account</h1>
          <p>Create a new account to manage your tickets.</p>
        </div>
        <form @submit.prevent="handle" class="auth-form">
          <div class="form-group">
            <label for="name">Full name</label>
            <input id="name" v-model="name" type="text" placeholder="Jane Doe" />
          </div>
          <div class="form-group">
            <label for="email">Email</label>
            <input id="email" v-model="email" type="email" placeholder="you@company.com" />
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input id="password" v-model="password" type="password" placeholder="At least 8 characters" />
          </div>

          <div v-if="error" class="form-error" role="alert">{{ error }}</div>

          <div class="actions">
            <button :disabled="loading" class="btn-submit btn primary">
              {{ loading ? 'Creating...' : 'Create Account' }}
            </button>
            <router-link to="/auth/login" class="btn ghost link-login">Have an account? Sign in</router-link>
          </div>
        </form>
      </div>
  </div>
</template>

<script>
import { signup } from '../../lib/api'
import { toast } from '../../lib/toast'
export default {
  data(){ return { name: '', email:'', password:'', error: null, loading: false } },
  methods:{
    async handle(){
      this.error = null
      if(!this.name || !this.email || !this.password){
        this.error = 'Please fill in all fields.'
        return
      }
      if(this.password.length < 8){
        this.error = 'Password must be at least 8 characters.'
        return
      }

      this.loading = true
      try{
        await signup({ name: this.name, email: this.email, password: this.password })
        toast('Account created. Redirecting...', 'success')
        this.$router.push('/dashboard')
      }catch(e){
        this.error = e.message || 'Failed to signup'
        toast(this.error, 'error')
      }finally{
        this.loading = false
      }
    }
  }
}
</script>

<style scoped>
.auth-page{min-height:80vh;display:flex;align-items:center;justify-content:center;padding:2rem}
.auth-card{width:100%;max-width:420px;background:var(--bg);border:1px solid var(--border-color);border-radius:12px;padding:1.5rem;box-shadow:var(--shadow-md)}
.auth-header h1{font-size:1.5rem;margin-bottom:0.25rem;color:var(--text)}
.auth-header p{color:var(--text-secondary);margin-bottom:1rem}
.auth-form{display:flex;flex-direction:column;gap:1rem}
.form-group{display:flex;flex-direction:column;gap:0.375rem}
.form-group label{font-size:0.875rem;font-weight:600;color:var(--text)}
.form-group input{padding:0.65rem;border-radius:8px;border:1px solid var(--border-color);background:rgba(99,102,241,0.06);font-size:0.95rem}
.form-error{color:var(--color-error);background:rgba(220,38,38,0.05);padding:0.5rem;border-radius:8px;border:1px solid rgba(220,38,38,0.08)}
.actions{display:flex;flex-direction:column;gap:0.75rem;margin-top:0.5rem}
.btn{padding:0.75rem;border-radius:10px;border:1px solid transparent;cursor:pointer}
.btn.primary{background:linear-gradient(90deg,var(--accent),var(--accent-hover));color:#fff}
.btn.primary[disabled]{opacity:0.6;cursor:not-allowed}
.btn.ghost{background:transparent;border-color:transparent;color:var(--text)}
.link-login{text-align:center;font-size:0.9rem;color:var(--text-secondary)}

@media (max-width:640px){
  .auth-card{padding:1rem;margin:1rem}
}
</style>

// react-implementation/src/pages/Auth/Signup.jsx
import React, { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { useAuth } from '../../hooks/useAuth';
import { pushToast } from '../../lib/toast';
import AuthLayout from '../../components/AuthLayout';

const EmailIcon = () => (
  <svg width="20" height="20" fill="none" strokeWidth="1.5" viewBox="0 0 24 24" stroke="currentColor">
    <path strokeLinecap="round" strokeLinejoin="round" d="M21.75 6.75v10.5a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25m19.5 0v.243a2.25 2.25 0 01-1.07 1.916l-7.5 4.615a2.25 2.25 0 01-2.36 0L3.32 8.91a2.25 2.25 0 01-1.07-1.916V6.75" />
  </svg>
);

const LockIcon = () => (
  <svg width="20" height="20" fill="none" strokeWidth="1.5" viewBox="0 0 24 24" stroke="currentColor">
    <path strokeLinecap="round" strokeLinejoin="round" d="M16.5 10.5V6.75a4.5 4.5 0 10-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 002.25-2.25v-6.75a2.25 2.25 0 00-2.25-2.25H6.75a2.25 2.25 0 00-2.25 2.25v6.75a2.25 2.25 0 002.25 2.25z" />
  </svg>
);

const Spinner = () => (
  <svg className="animate-spin h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
  </svg>
);

export default function Signup() {
  const [email, setEmail] = useState('');
  const [name, setName] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [errors, setErrors] = useState({});
  const [isLoading, setIsLoading] = useState(false);
  const { signup } = useAuth();
  const navigate = useNavigate();

  const validate = () => {
    const errors = {};
    if (!email) errors.email = 'Email is required';
    else if (!/\S+@\S+\.\S+/.test(email)) errors.email = 'Please enter a valid email';
    if (!name) errors.name = 'Name is required';
    if (!password) errors.password = 'Password is required';
    else if (password.length < 8) errors.password = 'Password must be at least 8 characters';
    if (!confirmPassword) errors.confirmPassword = 'Please confirm your password';
    else if (confirmPassword !== password) errors.confirmPassword = 'Passwords do not match';
    return errors;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    const validationErrors = validate();
    setErrors(validationErrors);
    if (Object.keys(validationErrors).length) return;

    setIsLoading(true);
    try {
      await signup({ email, password, name });
      pushToast({ msg: 'Account created successfully! Welcome aboard!', type: 'success' });
      navigate('/dashboard', { replace: true });
    } catch (err) {
      const message = err.code === 409
        ? 'This email is already registered'
        : 'Failed to create account. Please try again';
      setErrors({ form: message });
      pushToast({ msg: message, type: 'error' });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <AuthLayout
      title="Create your account"
      subtitle="Join us today to start managing your support tickets"
    >
      <form className="auth-form" onSubmit={handleSubmit}>
        {errors.form && (
          <div className="auth-alert error" role="alert">
            <svg width="20" height="20" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
            <span>{errors.form}</span>
          </div>
        )}

        <div className="form-group">
          <label htmlFor="name">Full Name</label>
          <div className="input-with-icon">
            <input
              id="name"
              type="text"
              className={`with-icon-left ${errors.name ? 'error' : ''}`}
              placeholder="Your name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              disabled={isLoading}
              autoComplete="name"
              autoFocus
            />
            <span className="input-icon left" aria-hidden="true">
              <svg width="20" height="20" fill="none" strokeWidth="1.5" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
              </svg>
            </span>
          </div>
          {errors.name && <span className="error-message">{errors.name}</span>}
        </div>

        <div className="form-group">
          <label htmlFor="email">Email address</label>
          <div className="input-with-icon">
            <input
              id="email"
              type="email"
              className={`with-icon-left ${errors.email ? 'error' : ''}`}
              placeholder="you@example.com"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              disabled={isLoading}
              autoComplete="email"
            />
            <span className="input-icon left" aria-hidden="true">
              <EmailIcon />
            </span>
          </div>
          {errors.email && <span className="error-message">{errors.email}</span>}
        </div>

        <div className="form-group">
          <label htmlFor="password">Password</label>
          <div className="input-with-icon">
            <input
              id="password"
              type="password"
              className={`with-icon-left ${errors.password ? 'error' : ''}`}
              placeholder="••••••••"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              disabled={isLoading}
              autoComplete="new-password"
            />
            <span className="input-icon left" aria-hidden="true">
              <LockIcon />
            </span>
          </div>
          {errors.password && <span className="error-message">{errors.password}</span>}
        </div>

        <div className="form-group">
          <label htmlFor="confirmPassword">Confirm password</label>
          <div className="input-with-icon">
            <input
              id="confirmPassword"
              type="password"
              className={`with-icon-left ${errors.confirmPassword ? 'error' : ''}`}
              placeholder="••••••••"
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
              disabled={isLoading}
              autoComplete="new-password"
            />
            <span className="input-icon left" aria-hidden="true">
              <LockIcon />
            </span>
          </div>
          {errors.confirmPassword && <span className="error-message">{errors.confirmPassword}</span>}
        </div>

        <button
          type="submit"
          className="btn-submit"
          disabled={isLoading}
        >
          <span className="flex items-center justify-center gap-2">
            {isLoading ? <Spinner /> : 'Create account'}
          </span>
        </button>

        <div className="auth-footer">
          Already have an account?{' '}
          <Link to="/auth/login">Sign in instead</Link>
        </div>
      </form>
    </AuthLayout>
  );
}
