// react-implementation/src/components/Footer.jsx
import React from 'react'
import '../styles/footer.css'

export default function Footer() {
  return ( 
    <footer className="site-footer" role="contentinfo">
      <div className="container footer-inner">
        <div className="footer-left">© {new Date().getFullYear()} Ticketr</div>
        <div className="footer-right">Accessible · Responsive · Lightweight</div>
      </div>
    </footer> 
  ) 
}

// vue-implementation/src/components/Footer.vue
<template>
  <footer class="site-footer" role="contentinfo">
    <div class="container footer-inner">
      <div class="footer-left">© {{ year }} Ticketr</div>
      <div class="footer-right">Accessible · Responsive · Lightweight</div>
    </div>
  </footer>
</template>

<script setup>
const year = new Date().getFullYear()
</script>

<style>
@import '../styles/components.css';
</style>
